[build-system]
requires = ['setuptools>=61.0']
build-backend = 'setuptools.build_meta'

[project]
name = 'xtreyspf'
version = '0.1.31'
authors = [
  { name='TheCursedOne' },
]
description = 'An extended add-on for pre-flop card evaluation.'
readme = 'README.md'
requires-python = '>=3.7'
classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
]
dependencies = [
    'treys'
]

[project.urls]
'Homepage' = 'https://github.com/bingchiliingsacker-dot/XtreysPF'

[pypi]
username = __token__
password = pypi-NEW_TOKEN_HERE
